spring:
  application:
    name: demo-circuit-breaker

resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      productService:
        max-attempts: 3          # total calls (1 original + 2 retries)
        wait-duration: 500ms     # delay between retries

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG
